name: adaptive_breakpoints
description: A Flutter package providing Material Design breakpoints for responsive layouts.
version: 0.1.4
repository: https://github.com/material-components/material-components-flutter-adaptive/tree/develop/adaptive_breakpoints

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
